//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorrectPlaceIdInformation.Schedulers {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttractionsDTO", Namespace="http://schemas.datacontract.org/2004/07/BusinessEntites.Common")]
    [System.SerializableAttribute()]
    public partial class AttractionsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressOneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressTwoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttractionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AttractionsIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoogleIConField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoogleInternational_phone_numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoogleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoogleRatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoogleSearchTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoogleUser_ratings_totalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoogleWebSiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Googleadr_addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RankIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressOne {
            get {
                return this.AddressOneField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressOneField, value) != true)) {
                    this.AddressOneField = value;
                    this.RaisePropertyChanged("AddressOne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressTwo {
            get {
                return this.AddressTwoField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressTwoField, value) != true)) {
                    this.AddressTwoField = value;
                    this.RaisePropertyChanged("AddressTwo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttractionName {
            get {
                return this.AttractionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AttractionNameField, value) != true)) {
                    this.AttractionNameField = value;
                    this.RaisePropertyChanged("AttractionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AttractionsId {
            get {
                return this.AttractionsIdField;
            }
            set {
                if ((this.AttractionsIdField.Equals(value) != true)) {
                    this.AttractionsIdField = value;
                    this.RaisePropertyChanged("AttractionsId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((this.CityIdField.Equals(value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoogleICon {
            get {
                return this.GoogleIConField;
            }
            set {
                if ((object.ReferenceEquals(this.GoogleIConField, value) != true)) {
                    this.GoogleIConField = value;
                    this.RaisePropertyChanged("GoogleICon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoogleInternational_phone_number {
            get {
                return this.GoogleInternational_phone_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.GoogleInternational_phone_numberField, value) != true)) {
                    this.GoogleInternational_phone_numberField = value;
                    this.RaisePropertyChanged("GoogleInternational_phone_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoogleName {
            get {
                return this.GoogleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GoogleNameField, value) != true)) {
                    this.GoogleNameField = value;
                    this.RaisePropertyChanged("GoogleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoogleRating {
            get {
                return this.GoogleRatingField;
            }
            set {
                if ((object.ReferenceEquals(this.GoogleRatingField, value) != true)) {
                    this.GoogleRatingField = value;
                    this.RaisePropertyChanged("GoogleRating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoogleSearchText {
            get {
                return this.GoogleSearchTextField;
            }
            set {
                if ((object.ReferenceEquals(this.GoogleSearchTextField, value) != true)) {
                    this.GoogleSearchTextField = value;
                    this.RaisePropertyChanged("GoogleSearchText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GoogleUser_ratings_total {
            get {
                return this.GoogleUser_ratings_totalField;
            }
            set {
                if ((this.GoogleUser_ratings_totalField.Equals(value) != true)) {
                    this.GoogleUser_ratings_totalField = value;
                    this.RaisePropertyChanged("GoogleUser_ratings_total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoogleWebSite {
            get {
                return this.GoogleWebSiteField;
            }
            set {
                if ((object.ReferenceEquals(this.GoogleWebSiteField, value) != true)) {
                    this.GoogleWebSiteField = value;
                    this.RaisePropertyChanged("GoogleWebSite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Googleadr_address {
            get {
                return this.Googleadr_addressField;
            }
            set {
                if ((object.ReferenceEquals(this.Googleadr_addressField, value) != true)) {
                    this.Googleadr_addressField = value;
                    this.RaisePropertyChanged("Googleadr_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlaceId {
            get {
                return this.PlaceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceIdField, value) != true)) {
                    this.PlaceIdField = value;
                    this.RaisePropertyChanged("PlaceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RankId {
            get {
                return this.RankIdField;
            }
            set {
                if ((this.RankIdField.Equals(value) != true)) {
                    this.RankIdField = value;
                    this.RaisePropertyChanged("RankId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Schedulers.ISchedulers")]
    public interface ISchedulers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchedulers/Admin_GetNearestLocations", ReplyAction="http://tempuri.org/ISchedulers/Admin_GetNearestLocationsResponse")]
        System.Collections.Generic.List<CorrectPlaceIdInformation.Schedulers.AttractionsDTO> Admin_GetNearestLocations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchedulers/Admin_GetNearestLocations", ReplyAction="http://tempuri.org/ISchedulers/Admin_GetNearestLocationsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CorrectPlaceIdInformation.Schedulers.AttractionsDTO>> Admin_GetNearestLocationsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISchedulersChannel : CorrectPlaceIdInformation.Schedulers.ISchedulers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchedulersClient : System.ServiceModel.ClientBase<CorrectPlaceIdInformation.Schedulers.ISchedulers>, CorrectPlaceIdInformation.Schedulers.ISchedulers {
        
        public SchedulersClient() {
        }
        
        public SchedulersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchedulersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedulersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedulersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<CorrectPlaceIdInformation.Schedulers.AttractionsDTO> Admin_GetNearestLocations() {
            return base.Channel.Admin_GetNearestLocations();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CorrectPlaceIdInformation.Schedulers.AttractionsDTO>> Admin_GetNearestLocationsAsync() {
            return base.Channel.Admin_GetNearestLocationsAsync();
        }
    }
}
